-- MySQL Script generated by MySQL Workbench
-- Mon May 14 17:40:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`IotDevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IotDevice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IotDevice` (
  `deviceId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `serialNumber` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`deviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeviceInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DeviceInfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DeviceInfo` (
  `id` INT NOT NULL,
  `version` INT NULL,
  `posX` INT NULL,
  `posY` INT NULL,
  `deviceId` INT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `deviceIdFK_idx` (`deviceId` ASC),
  CONSTRAINT `deviceIdFK`
    FOREIGN KEY (`deviceId`)
    REFERENCES `mydb`.`IotDevice` (`deviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
